<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="12"
           failures="4"
           errors="0"
           skipped="0"
           time="37.392">
  <properties />
            <testcase name="LoginWithAccounts" time="3.731" classname="com.testcase.Login.Test_LoginFunction">
                <failure type="java.lang.AssertionError"
                  message="Login failed with: tuan002@example.com expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: Login failed with: tuan002@example.com expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  com.testcase.Login.Test_LoginFunction.LoginWithAccounts(Test_LoginFunction.java:91)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1623)
]]>
      </failure>

          </testcase>
            <testcase name="LoginWithAccounts" time="2.934" classname="com.testcase.Login.Test_LoginFunction">
                <failure type="java.lang.AssertionError"
                  message="Login failed with: tuan003@example.com expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: Login failed with: tuan003@example.com expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  com.testcase.Login.Test_LoginFunction.LoginWithAccounts(Test_LoginFunction.java:91)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1623)
]]>
      </failure>

          </testcase>
            <testcase name="LoginWithAccounts" time="2.786" classname="com.testcase.Login.Test_LoginFunction">
                <failure type="java.lang.AssertionError"
                  message="Login failed with: tuan004@example.com expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: Login failed with: tuan004@example.com expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  com.testcase.Login.Test_LoginFunction.LoginWithAccounts(Test_LoginFunction.java:91)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1623)
]]>
      </failure>

          </testcase>
            <testcase name="LoginWithAccounts" time="3.313" classname="com.testcase.Login.Test_LoginFunction">
                <failure type="java.lang.AssertionError"
                  message="Login failed with: tuan006@example.com expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: Login failed with: tuan006@example.com expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  com.testcase.Login.Test_LoginFunction.LoginWithAccounts(Test_LoginFunction.java:91)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1623)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC04_isPasswordTextBoxEnabled" time="0.019" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="TC03_isPasswordTextBoxDisplayed" time="0.044" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="TC05_isLoginButtonDisplayed" time="0.027" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="TC02_isEmailTextBoxEnabled" time="0.035" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="LoginWithAccounts" time="12.028" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="TC01_isEmailTextBoxDisplayed" time="2.081" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="LoginWithAccounts" time="10.372" classname="com.testcase.Login.Test_LoginFunction" />
                <testcase name="TC06_isLoginButtonEnabled" time="0.022" classname="com.testcase.Login.Test_LoginFunction" />
      
</testsuite>
